name: Jenkins Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: unit-test

jobs:
  Jenkins-Editor-Testing:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Variables
        run: |
          echo "$CI_HEAD_REF"
      - name: Print
        run: echo ${{ env.CI_ACTION_REF_NAME }}
      - name: Trigger-unit-test
        uses: SimonMaghiar/jenkins-trigger@main      
        with:
          url:  ${{ secrets.JENKINS_URL }}
          user_name: ${{ secrets.JENKINS_USER }} # user name for accessing jenkins
          api_token: ${{ secrets.JENKINS_PAT }} # personal Access token for accessing Jenkins
          job_name: "Pipeline-Editor-Testing" # The name of the jenkins job to run
          parameter: '{"branch": "${{ env.CI_ACTION_REF_NAME }}", "repo":"${{ env.CI_REPOSITORY_NAME }}", "base":"${{ env.CI_BASE_REF }}"}'
          timeout: "5000"